name: Docker Image CI

on:
  push:
    tags: 
    - "*"  # Matches all tags (e.g., v1.0.0, release-2025, etc.)

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build . --file Containerfile --tag jetbrains-devcontainer-clients:${GITHUB_REF#refs/tags/}
