name: Docker Image CI

on:
  push:
    tags:
      - "*"  # Runs on all tags

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout the code
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PW }}" | docker login -u "${{ secrets.DOCKER_USER }}" --password-stdin

    - name: Build the Docker image
      run: docker build . --file Containerfile --tag deedss/jetbrains-devcontainer-clients:${GITHUB_REF#refs/tags/}

    - name: Push the Docker image to Docker Hub
      run: docker push deedss/jetbrains-devcontainer-clients:${GITHUB_REF#refs/tags/}
